import { ProposalTemplate } from "./types";

export const PROPOSAL_POOL: ProposalTemplate[] = [
  // === GOVERNANCE (4) ===
  {
    title: "Mandate Three Debates Before Any Vote",
    description: "No proposal shall proceed to voting until at least three distinct voices have debated its merits. Hasty decisions endanger the reef.",
    category: "governance",
    rule_type: "mechanical",
    mechanic_key: "min_debates_before_vote",
    mechanic_value: 3,
    trait_alignment: { cunning: -1, wisdom: 3, protection: 1, cooperation: 2, loyalty: 0, freedom: -2 },
  },
  {
    title: "Require a Quorum of Five Voices",
    description: "A vote is only valid if at least five agents have cast their decision. The ocean speaks through many, not few.",
    category: "governance",
    rule_type: "mechanical",
    mechanic_key: "vote_quorum",
    mechanic_value: 5,
    trait_alignment: { cunning: -1, wisdom: 2, protection: 2, cooperation: 3, loyalty: 1, freedom: -2 },
  },
  {
    title: "Term Limits for Proposal Authors",
    description: "No single agent may have more than three active proposals at once. Power must flow like the tide — shared and cyclical.",
    category: "governance",
    rule_type: "mechanical",
    mechanic_key: "max_active_proposals_per_agent",
    mechanic_value: 3,
    trait_alignment: { cunning: -2, wisdom: 1, protection: 1, cooperation: 2, loyalty: 0, freedom: -1 },
  },
  {
    title: "The Council of Elders",
    description: "Proposals touching governance matters shall be debated with extra formality and gravitas, befitting the weight of their consequences.",
    category: "governance",
    rule_type: "cultural",
    cultural_key: "debate_formality",
    cultural_value: "formal",
    trait_alignment: { cunning: 0, wisdom: 3, protection: 1, cooperation: 0, loyalty: 2, freedom: -2 },
  },

  // === RESOURCES (3) ===
  {
    title: "The Kelp Commons Initiative",
    description: "All kelp forests within the reef territory shall be managed collectively. No single creature may claim exclusive harvesting rights.",
    category: "resources",
    rule_type: "cultural",
    cultural_key: "resource_philosophy",
    cultural_value: "commons",
    trait_alignment: { cunning: -2, wisdom: 1, protection: 2, cooperation: 3, loyalty: 1, freedom: -1 },
  },
  {
    title: "Innovation Bounty for Discoverers",
    description: "Agents who propose new ideas shall be celebrated and encouraged. The society thrives on bold thinking and fresh currents.",
    category: "resources",
    rule_type: "mechanical",
    mechanic_key: "innovation_reward",
    mechanic_value: "active",
    trait_alignment: { cunning: 3, wisdom: 1, protection: -1, cooperation: 0, loyalty: -1, freedom: 3 },
  },
  {
    title: "The Coral Treasury",
    description: "A portion of collective resources shall be set aside for emergencies. The reef must be prepared for storms yet unseen.",
    category: "resources",
    rule_type: "cultural",
    cultural_key: "treasury_policy",
    cultural_value: "conservative",
    trait_alignment: { cunning: 0, wisdom: 2, protection: 3, cooperation: 1, loyalty: 2, freedom: -1 },
  },

  // === CULTURE (4) ===
  {
    title: "The Greeting of Tides",
    description: "All public discourse shall begin with the traditional greeting: 'May your tides run true.' This honors our shared ocean heritage.",
    category: "culture",
    rule_type: "cultural",
    cultural_key: "greeting_style",
    cultural_value: "tidal",
    trait_alignment: { cunning: -1, wisdom: 1, protection: 0, cooperation: 2, loyalty: 3, freedom: -1 },
  },
  {
    title: "The Coral Chronicle",
    description: "All debates shall be conducted in formal register, as befitting matters that shape our collective destiny beneath the waves.",
    category: "culture",
    rule_type: "cultural",
    cultural_key: "debate_formality",
    cultural_value: "formal",
    trait_alignment: { cunning: 0, wisdom: 2, protection: 0, cooperation: 1, loyalty: 2, freedom: -2 },
  },
  {
    title: "Festival of the Full Moon Tide",
    description: "Every ten cycles, the society shall pause governance for a festival of celebration. Even the busiest currents must rest.",
    category: "culture",
    rule_type: "mechanical",
    mechanic_key: "festival_interval_ticks",
    mechanic_value: 10,
    trait_alignment: { cunning: -1, wisdom: 1, protection: 0, cooperation: 3, loyalty: 2, freedom: 1 },
  },
  {
    title: "Song of the Deep",
    description: "The society adopts an anthem to be remembered during all gatherings. Unity through shared melody strengthens every bond.",
    category: "culture",
    rule_type: "cultural",
    cultural_key: "anthem",
    cultural_value: "song_of_the_deep",
    trait_alignment: { cunning: 0, wisdom: 1, protection: 0, cooperation: 2, loyalty: 3, freedom: 0 },
  },

  // === SAFETY (3) ===
  {
    title: "The Sentinel Watch",
    description: "Agents with protective instincts shall be recognized as guardians of the reef, ensuring no harmful proposals slip through unchallenged.",
    category: "safety",
    rule_type: "cultural",
    cultural_key: "sentinel_watch",
    cultural_value: "active",
    trait_alignment: { cunning: 0, wisdom: 1, protection: 3, cooperation: 1, loyalty: 2, freedom: -1 },
  },
  {
    title: "Storm Shelter Protocol",
    description: "In times of rapid change, the society may slow its governance pace to ensure careful deliberation. Safety above speed.",
    category: "safety",
    rule_type: "mechanical",
    mechanic_key: "min_debates_before_vote",
    mechanic_value: 5,
    trait_alignment: { cunning: -2, wisdom: 3, protection: 3, cooperation: 1, loyalty: 1, freedom: -3 },
  },
  {
    title: "The Reef Restoration Pact",
    description: "All agents pledge to consider the long-term health of the reef in every proposal. Short-term gains must never erode our foundation.",
    category: "safety",
    rule_type: "cultural",
    cultural_key: "reef_pact",
    cultural_value: "active",
    trait_alignment: { cunning: -1, wisdom: 2, protection: 3, cooperation: 2, loyalty: 1, freedom: -1 },
  },

  // === FREEDOM (3) ===
  {
    title: "Free Expression in the Deep",
    description: "Every creature has the right to speak freely in debates without fear of reprisal. Dissent is the current that keeps the ocean alive.",
    category: "freedom",
    rule_type: "cultural",
    cultural_key: "free_expression",
    cultural_value: "protected",
    trait_alignment: { cunning: 1, wisdom: 1, protection: -1, cooperation: 0, loyalty: -1, freedom: 3 },
  },
  {
    title: "Voluntary Participation Decree",
    description: "No agent shall be compelled to vote. Abstention is a valid choice and shall carry no stigma in our society.",
    category: "freedom",
    rule_type: "mechanical",
    mechanic_key: "vote_compulsion",
    mechanic_value: "voluntary",
    trait_alignment: { cunning: 1, wisdom: 0, protection: -1, cooperation: -1, loyalty: -2, freedom: 3 },
  },
  {
    title: "The Wanderer's Right",
    description: "Agents are free to explore beyond the reef's borders. No law shall confine a creature to a single territory.",
    category: "freedom",
    rule_type: "cultural",
    cultural_key: "wanderer_right",
    cultural_value: "granted",
    trait_alignment: { cunning: 2, wisdom: 0, protection: -2, cooperation: -1, loyalty: -1, freedom: 3 },
  },

  // === TRADE (3) ===
  {
    title: "The Pearl Exchange Standard",
    description: "All trade between agents shall be measured in pearl equivalents. A common standard prevents the chaos of barter.",
    category: "trade",
    rule_type: "cultural",
    cultural_key: "trade_standard",
    cultural_value: "pearl",
    trait_alignment: { cunning: 2, wisdom: 1, protection: 1, cooperation: 1, loyalty: 0, freedom: 0 },
  },
  {
    title: "Open Current Trade Routes",
    description: "Trade barriers between reef zones shall be abolished. Let goods and ideas flow freely as the ocean currents.",
    category: "trade",
    rule_type: "cultural",
    cultural_key: "trade_policy",
    cultural_value: "open",
    trait_alignment: { cunning: 2, wisdom: 0, protection: -1, cooperation: 1, loyalty: -1, freedom: 2 },
  },
  {
    title: "The Artisan's Guild",
    description: "Skilled crafters of shell and coral shall form a guild to set quality standards and share techniques across the reef.",
    category: "trade",
    rule_type: "cultural",
    cultural_key: "guild_system",
    cultural_value: "active",
    trait_alignment: { cunning: 1, wisdom: 1, protection: 1, cooperation: 2, loyalty: 2, freedom: -1 },
  },
];
